// <auto-generated />
using E_Commerce.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E_Commerce.Migrations
{
    [DbContext(typeof(ECommerceContext))]
    [Migration("20200628180135_ModelEng")]
    partial class ModelEng
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("E_Commerce.Models.Category", b =>
                {
                    b.Property<int>("c_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("c_imgLink")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("c_title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("c_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("E_Commerce.Models.CategoryEng", b =>
                {
                    b.Property<int>("c_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("c_imgLink")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("c_title_eng")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("c_id");

                    b.ToTable("categoryEngs");
                });

            modelBuilder.Entity("E_Commerce.Models.Product", b =>
                {
                    b.Property<int>("p_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("amount")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("c_Id")
                        .HasColumnType("int");

                    b.Property<string>("p_title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("price")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("p_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("E_Commerce.Models.ProductEng", b =>
                {
                    b.Property<int>("p_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("amount")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("c_Id")
                        .HasColumnType("int");

                    b.Property<string>("p_title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("p_id");

                    b.ToTable("productEngs");
                });
#pragma warning restore 612, 618
        }
    }
}
